### ISSUE TITLE
Migration fails

### ISSUE THREAD

**Issue by zos-jeff-olen** [notch8/rent_my_thing#28]
LEARN01:rent_my_thing learn01$ rake db:migrate
== 20150227182207 CreateCategories: migrating =================================
-- create_table(:categories)
   -> 0.0344s
== 20150227182207 CreateCategories: migrated (0.0345s) ========================

== 20150227182208 CreatePostings: migrating ===================================
-- create_table(:postings)
   -> 0.0054s
-- add_foreign_key(:postings, :categories)
   -> 0.0016s
== 20150227182208 CreatePostings: migrated (0.0072s) ==========================

== 20150227185818 DeviseCreateUsers: migrating ================================
-- create_table(:users)
   -> 0.0370s
-- add_index(:users, :email, {:unique=>true})
   -> 0.0025s
-- add_index(:users, :reset_password_token, {:unique=>true})
   -> 0.0020s
== 20150227185818 DeviseCreateUsers: migrated (0.0416s) =======================

== 20150227192939 AddStateToPostings: migrating ===============================
-- add_column(:postings, :state, :string)
   -> 0.0006s
== 20150227192939 AddStateToPostings: migrated (0.0006s) ======================

== 20150302194131 ChangeColumunInPostings: migrating ==========================
-- change_column(:postings, :street, :string, {:limit=>20})
   -> 0.0050s
== 20150302194131 ChangeColumunInPostings: migrated (0.0051s) =================

== 20150302200543 AddCityToPostings: migrating ================================
-- add_column(:postings, :city, :string, {:limit=>30})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "city" of relation "postings" already exists
: ALTER TABLE "postings" ADD "city" character varying(30)/Users/learn01/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/learn01/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in`block in execute'
/Users/learn01/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
/Users/learn01/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/notifications/instrume

**Comment by zos-jeff-olen** [comment]
Fixed as part of the "migration-fix" merge
